# Change these first
owner: monitorapp-aicc
repo: ailabs-status

sites:
  - name: ailabs
    url: https://ailabs.monitorapp.com
  # File Analysis
  - name: File analysis
    url: https://ailabs-api.monitorapp.com/v1/analysis/file
    method: POST
    maxResponseTime: 10000
    expectedStatusCodes:
      - 400
    headers:
    - "Authorization: $API_KEY"
  - name: Inquiring file status
    url: https://ailabs-api.monitorapp.com/v1/analysis/file/status?id=100
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    headers:
    - "Authorization: $API_KEY"
  - name: Inquiring file result
    url: https://ailabs-api.monitorapp.com/v1/analysis/file/result?id=100
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    headers:
    - "Authorization: $API_KEY"
  # URL Analysis
  - name: URL analysis
    url: https://ailabs-api.monitorapp.com/v1/analysis/url
    method: POST
    maxResponseTime: 10000
    headers:
      - "Content-Type: application/json"
      - "Authorization: $API_KEY"
    body: '{ "url": "https://wwww.example.com" }'
  - name: Bulk URL analysis
    url: https://ailabs-api.monitorapp.com/v1/analysis/url/bulk
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
      - "Content-Type: application/json"
    body: '{ "urls": ["https://wwww.example.com"] }'
  - name: Bulk URL analysis results list query by task ID
    url: https://ailabs-api.monitorapp.com/v1/analysis/url/bulk/task_list
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"    
      - "Content-Type: application/json"
    body: '{ "request_id": "50341510-4e57-4b99-a398-97c43a79d9c5" }'
  - name: Inquiring URL result
    url: https://ailabs-api.monitorapp.com/v1/analysis/url/result?id=50341510-4e57-4b99-a398-97c43a79d9c5
    method: GET
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"    
  - name: Malicious URL match
    url: https://ailabs-api.monitorapp.com/v1/search/url/malicious
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
      - "Content-Type: application/json"
    body: '[ { "url" : "https://www.example.com" } ]'
  # URL Category
  - name: Inquiring URL Category
    url: https://ailabs-api.monitorapp.com/v1/search/url/category
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
      - "Content-Type: application/json"
    body: '[ { "url" : "https://www.example.com" } ]'
  # Log Search
  - name: Web attacker ip match request
    url: https://ailabs-api.monitorapp.com/v1/search/ip/attacker
    method: GET
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
      - "Content-Type: application/json"
    body: '[ { "ip" : "10.0.0.1" } ]'
  - name: Malicious file match request
    url: https://ailabs-api.monitorapp.com/v1/search/file/malicious
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
  # Log Search
  - name: Search bot category
    url: https://ailabs-api.monitorapp.com/v1/search/bot/category
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
      - "Content-Type: application/json"
    body: '[ { "ip" : "10.0.0.1" } ]'
  - name: Search bot match
    url: https://ailabs-api.monitorapp.com/v1/search/bot/match
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
      - "Content-Type: application/json"
    body: '[ { "ip" : "10.0.0.1" } ]'
  # IP Reputation
  - name: Search bot category
    url: https://ailabs-api.monitorapp.com/v1/search/ip_reputation?ip=10.0.0.1&start=2025-05-01&end=2025-05-02
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
  # IP Reputation
  - name: Mis URL report
    url: https://ailabs-api.monitorapp.com/v1/ailabs/url/mis_report
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
  - name: Mis IP report
    url: https://ailabs-api.monitorapp.com/v1/ailabs/ip/mis_report
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"
  - name: Mis report history
    url: https://ailabs-api.monitorapp.com/v1/ailabs/api/mis_report
    method: POST
    maxResponseTime: 10000
    headers:
      - "Authorization: $API_KEY"

      
status-website:
  baseUrl: /ailabs-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AiLabs Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: AiLabs
      href: https://ailabs.monitorapp.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
